# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-18 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_type', models.CharField(blank=True, max_length=100)),
                ('mls', models.CharField(blank=True, max_length=100)),
                ('agentid', models.CharField(blank=True, max_length=100)),
                ('user_name', models.CharField(blank=True, max_length=100)),
                ('user_tel', models.CharField(blank=True, max_length=100)),
                ('user_email', models.CharField(blank=True, max_length=100)),
                ('user_msg', models.CharField(blank=True, max_length=1000)),
                ('user_ip', models.CharField(blank=True, max_length=100)),
                ('src_url', models.CharField(blank=True, max_length=1000)),
                ('datadate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '\u6d88\u606f\u7559\u8a00\u4e2d\u5fc3',
                'verbose_name_plural': '\u6d88\u606f\u7559\u8a00\u4e2d\u5fc3',
            },
        ),
    ]
