# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-07 13:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article_content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articleid', models.CharField(blank=True, max_length=100)),
                ('pid', models.IntegerField(default=0)),
                ('ptype', models.CharField(blank=True, max_length=100)),
                ('pstyle', models.CharField(blank=True, max_length=100)),
                ('p', models.CharField(blank=True, max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Article_img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articleid', models.CharField(blank=True, max_length=100)),
                ('imgname', models.CharField(blank=True, max_length=300)),
                ('img', models.FileField(upload_to=b'articleimg')),
                ('datadate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Article_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articleid', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('author', models.CharField(blank=True, max_length=100)),
                ('publishdate', models.CharField(blank=True, max_length=100)),
                ('srcurl', models.CharField(blank=True, max_length=500)),
                ('articletype', models.CharField(blank=True, max_length=100)),
                ('datadate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='article_content',
            name='img',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.Article_img'),
        ),
    ]
