# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-07 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article_img',
            name='img',
            field=models.FileField(null=True, upload_to=b'articleimg'),
        ),
    ]
