# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_article_info_instr'),
    ]

    operations = [
        migrations.AddField(
            model_name='article_content',
            name='pimg',
            field=models.FileField(blank=True, upload_to=b'articleimg'),
        ),
        migrations.AddField(
            model_name='article_info',
            name='img',
            field=models.FileField(blank=True, upload_to=b'articleimg'),
        ),
    ]
