# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20170306_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='article_info',
            name='authorurl',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
