# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_article_info_authorurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='article_info',
            name='articlecate',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='article_info',
            name='src',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
