# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-13 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address_book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=50)),
                ('recvname', models.CharField(max_length=50)),
                ('recvtel', models.CharField(max_length=50)),
                ('addr', models.CharField(blank=True, max_length=1000)),
                ('addr_type', models.CharField(max_length=50)),
                ('createdate', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '\u5730\u5740\u8868',
                'verbose_name_plural': '\u5730\u5740\u8868',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_id', models.CharField(blank=True, max_length=100)),
                ('product_id', models.CharField(max_length=50)),
                ('set_price', models.CharField(blank=True, max_length=1000)),
                ('userid', models.CharField(max_length=50)),
                ('tel', models.CharField(max_length=50)),
                ('addr', models.CharField(blank=True, max_length=1000)),
                ('order_status', models.CharField(max_length=50)),
                ('createdate', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '\u8ba2\u5355\u8868',
                'verbose_name_plural': '\u8ba2\u5355\u8868',
            },
        ),
        migrations.CreateModel(
            name='Product_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=50)),
                ('product_name', models.CharField(blank=True, max_length=100)),
                ('product_title', models.CharField(blank=True, max_length=1000)),
                ('product_desc', models.CharField(blank=True, max_length=1000)),
                ('price', models.CharField(blank=True, max_length=100)),
                ('product_img', models.FileField(blank=True, upload_to='product_imgs')),
                ('createdate', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '\u5546\u54c1\u4fe1\u606f\u8868',
                'verbose_name_plural': '\u5546\u54c1\u4fe1\u606f\u8868',
            },
        ),
        migrations.CreateModel(
            name='Product_sets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_id', models.CharField(blank=True, max_length=100)),
                ('product_id', models.CharField(max_length=50)),
                ('set_name', models.CharField(blank=True, max_length=1000)),
                ('set_price', models.CharField(blank=True, max_length=1000)),
                ('createdate', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '\u5546\u54c1\u5957\u9910\u8868',
                'verbose_name_plural': '\u5546\u54c1\u5957\u9910\u8868',
            },
        ),
    ]
