# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-13 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0002_address_book_orders_product_info_product_sets'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=50)),
                ('orderid', models.IntegerField()),
                ('product_text', models.CharField(blank=True, max_length=1000)),
                ('product_img', models.FileField(blank=True, upload_to='product_imgs')),
            ],
            options={
                'verbose_name': '\u5546\u54c1\u8be6\u60c5\u8868',
                'verbose_name_plural': '\u5546\u54c1\u8be6\u60c5\u8868',
            },
        ),
    ]
