# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-13 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0004_product_detail_detail_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='address_book',
            name='addrid',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='address_book',
            name='addr_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='address_book',
            name='recvname',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='address_book',
            name='recvtel',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='address_book',
            name='userid',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
