# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing_for_sp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listingid', models.CharField(max_length=50)),
                ('listingname', models.CharField(max_length=100)),
                ('cityname', models.CharField(db_index=True, max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('areas', models.CharField(max_length=100)),
                ('bedroom', models.CharField(max_length=100)),
                ('toilet', models.CharField(max_length=100)),
                ('parking', models.CharField(max_length=100)),
                ('tax', models.CharField(max_length=100)),
                ('housetype', models.CharField(max_length=100)),
                ('housestyle', models.CharField(max_length=100)),
                ('basement', models.CharField(max_length=100)),
                ('builddate', models.CharField(max_length=100)),
                ('intro', models.TextField()),
                ('goodat', models.TextField()),
                ('corp', models.CharField(max_length=500)),
                ('warning', models.TextField()),
                ('url', models.CharField(max_length=300)),
                ('intro_zh', models.TextField(blank=True, default='')),
                ('datadate', models.DateTimeField(auto_now_add=True)),
                ('schoolid', models.CharField(blank=True, max_length=100)),
                ('good', models.IntegerField(default=0)),
                ('visit', models.IntegerField(default=0)),
                ('postid', models.CharField(blank=True, max_length=30)),
                ('lat', models.CharField(blank=True, max_length=30)),
                ('lng', models.CharField(blank=True, max_length=30)),
                ('token', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'verbose_name': '\u5728\u552e\u623f\u6e90',
                'verbose_name_plural': '\u5728\u552e\u623f\u6e90',
            },
        ),
        migrations.CreateModel(
            name='Open_house',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listingid', models.CharField(max_length=50)),
                ('openhosue1', models.CharField(blank=True, max_length=100)),
                ('openhosue2', models.CharField(blank=True, max_length=100)),
                ('openhosue3', models.CharField(blank=True, max_length=100)),
                ('openhosue4', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tokens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=30)),
                ('tokentype', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('active', models.CharField(max_length=1)),
            ],
        ),
    ]
