# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singlepage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='open_house',
            old_name='openhosue1',
            new_name='date1',
        ),
        migrations.RenameField(
            model_name='open_house',
            old_name='openhosue2',
            new_name='date2',
        ),
        migrations.RenameField(
            model_name='open_house',
            old_name='openhosue3',
            new_name='date3',
        ),
        migrations.RenameField(
            model_name='open_house',
            old_name='openhosue4',
            new_name='date4',
        ),
        migrations.AddField(
            model_name='open_house',
            name='time1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='open_house',
            name='time2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='open_house',
            name='time3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='open_house',
            name='time4',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
