# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 05:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singlepage', '0002_auto_20170706_0023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Call_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listingid', models.CharField(max_length=30)),
                ('agentid', models.CharField(blank=True, max_length=30)),
                ('username', models.CharField(max_length=30)),
                ('tel', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('ip', models.CharField(blank=True, max_length=20)),
                ('datadate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
