# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-15 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singlepage', '0003_call_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sp_img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listingid', models.CharField(max_length=50)),
                ('imgtype', models.CharField(blank=True, max_length=100)),
                ('img', models.FileField(upload_to='sp_imgs')),
            ],
        ),
        migrations.CreateModel(
            name='User_information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('username', models.CharField(blank=True, max_length=50)),
                ('tel', models.CharField(blank=True, max_length=30)),
                ('website', models.CharField(blank=True, max_length=1000)),
                ('introduction', models.CharField(blank=True, max_length=5000)),
                ('head', models.FileField(upload_to='sp_users')),
                ('cn_username', models.CharField(blank=True, max_length=50)),
                ('cn_tel', models.CharField(blank=True, max_length=50)),
                ('cn_email', models.CharField(blank=True, max_length=100)),
                ('cn_head', models.FileField(upload_to='sp_users')),
                ('cn_QR', models.FileField(upload_to='sp_users')),
            ],
        ),
    ]
