# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-15 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singlepage', '0004_sp_img_user_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokens',
            name='userid',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
