# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-15 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singlepage', '0005_tokens_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_information',
            name='logo',
            field=models.FileField(blank=True, upload_to='sp_users'),
        ),
        migrations.AlterField(
            model_name='sp_img',
            name='img',
            field=models.FileField(blank=True, upload_to='sp_imgs'),
        ),
        migrations.AlterField(
            model_name='user_information',
            name='cn_QR',
            field=models.FileField(blank=True, upload_to='sp_users'),
        ),
        migrations.AlterField(
            model_name='user_information',
            name='cn_head',
            field=models.FileField(blank=True, upload_to='sp_users'),
        ),
        migrations.AlterField(
            model_name='user_information',
            name='head',
            field=models.FileField(blank=True, upload_to='sp_users'),
        ),
    ]
