# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-26 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singlepage', '0007_listing_for_sp_vrtour'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='call_history',
            options={'verbose_name': '\u7528\u6237\u7559\u8a00\u4fe1\u606f', 'verbose_name_plural': '\u7528\u6237\u7559\u8a00\u4fe1\u606f'},
        ),
        migrations.AlterModelOptions(
            name='open_house',
            options={'verbose_name': '\u516c\u4f17\u5f00\u653e\u65e5', 'verbose_name_plural': '\u516c\u4f17\u5f00\u653e\u65e5'},
        ),
        migrations.AlterModelOptions(
            name='sp_img',
            options={'verbose_name': '\u623f\u6e90\u56fe\u7247\u53ca\u89c6\u9891', 'verbose_name_plural': '\u623f\u6e90\u56fe\u7247\u53ca\u89c6\u9891'},
        ),
        migrations.AlterModelOptions(
            name='user_information',
            options={'verbose_name': '\u5ba2\u6237\u4fe1\u606f', 'verbose_name_plural': '\u5ba2\u6237\u4fe1\u606f'},
        ),
        migrations.AlterField(
            model_name='sp_img',
            name='imgtype',
            field=models.CharField(choices=[('hx', '\u6237\u578b\u56fe'), ('video', '\u89c6\u9891'), ('bgimg1', '\u7b2c\u4e00\u5e45\u80cc\u666f\u56fe'), ('bgimg2', '\u7b2c\u4e8c\u5e45\u80cc\u666f\u56fe'), ('bgimg3', '\u7b2c\u4e09\u5e45\u80cc\u666f\u56fe'), ('bgimg4', '\u7b2c\u56db\u5e45\u80cc\u666f\u56fe'), ('bgimg5', '\u7b2c\u4e94\u5e45\u80cc\u666f\u56fe')], max_length=100),
        ),
    ]
