# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-26 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singlepage', '0008_auto_20170726_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sp_img',
            name='imgtype',
            field=models.CharField(choices=[('hx', '\u6237\u578b\u56fe'), ('video', '\u89c6\u9891'), ('pdf', 'PDF'), ('bgimg1', '\u7b2c\u4e00\u5e45\u80cc\u666f\u56fe'), ('bgimg2', '\u7b2c\u4e8c\u5e45\u80cc\u666f\u56fe'), ('bgimg3', '\u7b2c\u4e09\u5e45\u80cc\u666f\u56fe'), ('bgimg4', '\u7b2c\u56db\u5e45\u80cc\u666f\u56fe'), ('bgimg5', '\u7b2c\u4e94\u5e45\u80cc\u666f\u56fe')], max_length=100),
        ),
    ]
