# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-30 04:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singlepage', '0010_auto_20170727_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing_for_sp',
            name='titleagent',
            field=models.CharField(default='0', max_length=1),
        ),
    ]
