# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-08 04:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singlepage', '0012_auto_20170731_2310'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flow_statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addr', models.CharField(blank=True, max_length=100)),
                ('htmlid', models.CharField(blank=True, max_length=1000)),
                ('htmltype', models.CharField(blank=True, max_length=10)),
                ('userid', models.CharField(blank=True, max_length=100)),
                ('datadate', models.DateTimeField(auto_now_add=True)),
                ('agent', models.CharField(blank=True, max_length=1000)),
                ('referer', models.CharField(blank=True, max_length=1000)),
                ('sess', models.CharField(blank=True, max_length=1000)),
            ],
        ),
    ]
