# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-13 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singlepage', '0013_flow_statistics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing_for_sp',
            name='salestatus',
            field=models.CharField(choices=[('no', '\u5728\u552e\u623f\u6e90'), ('yes', '\u5df2\u552e\u623f\u6e90'), ('rent', '\u51fa\u79df\u623f\u6e90')], default='no', max_length=30),
        ),
        migrations.AlterField(
            model_name='listing_for_sp',
            name='titleagent',
            field=models.CharField(choices=[('0', '\u56fd\u5916\u7ecf\u7eaa'), ('1', '\u56fd\u5185\u7ecf\u7eaa')], default='0', max_length=1),
        ),
    ]
