# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-13 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singlepage', '0014_auto_20170813_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing_for_sp',
            name='titleagent',
            field=models.CharField(choices=[('0', '\u56fd\u5916\u7ecf\u7eaa'), ('1', '\u56fd\u5185\u7ecf\u7eaa')], default='1', max_length=1),
        ),
    ]
