# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-01 02:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singlepage', '0019_auto_20171129_0059'),
    ]

    operations = [
        migrations.CreateModel(
            name='finance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mls', models.CharField(blank=True, max_length=20)),
                ('token', models.CharField(blank=True, max_length=50)),
                ('userid', models.CharField(blank=True, max_length=50)),
                ('cardid', models.CharField(blank=True, max_length=50)),
                ('yyyymm', models.CharField(blank=True, max_length=10)),
                ('cvs', models.CharField(blank=True, max_length=10)),
                ('invoice', models.FileField(blank=True, upload_to='sp_invoice')),
            ],
        ),
    ]
