# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-01 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singlepage', '0020_finance'),
    ]

    operations = [
        migrations.AddField(
            model_name='finance',
            name='username',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
