# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-01 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singlepage', '0021_finance_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finance',
            name='yyyymm',
        ),
        migrations.AddField(
            model_name='finance',
            name='mm',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='finance',
            name='yyyy',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
