# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-02 01:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singlepage', '0022_auto_20171201_1549'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='finance',
            options={'verbose_name': '\u53d1\u7968\u3001\u4fe1\u7528\u5361\u4fe1\u606f', 'verbose_name_plural': '\u53d1\u7968\u3001\u4fe1\u7528\u5361\u4fe1\u606f'},
        ),
        migrations.AddField(
            model_name='finance',
            name='status',
            field=models.CharField(choices=[('paid', '\u5df2\u652f\u4ed8'), ('not paid', '\u672a\u652f\u4ed8'), ('ubertor', 'Uberotr\u652f\u4ed8')], default='not paid', max_length=50),
        ),
    ]
