# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-08 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singlepage', '0023_auto_20171202_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing_for_sp',
            name='listingtype',
            field=models.CharField(blank=True, default='\u7279\u8272\u623f\u6e90', max_length=500),
        ),
    ]
