# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-20 01:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singlepage', '0024_listing_for_sp_listingtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='card_update_record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mls', models.CharField(blank=True, max_length=20)),
                ('token', models.CharField(blank=True, max_length=50)),
                ('userid', models.CharField(blank=True, max_length=50)),
                ('username', models.CharField(blank=True, max_length=100)),
                ('cardid', models.CharField(blank=True, max_length=50)),
                ('yyyy', models.CharField(blank=True, max_length=4)),
                ('mm', models.CharField(blank=True, max_length=2)),
                ('cvs', models.CharField(blank=True, max_length=10)),
                ('lastdate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='listing_for_sp',
            name='lastdate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
