# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-14 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singlepage', '0025_auto_20171220_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='sp_img',
            name='owner',
            field=models.FileField(blank=True, upload_to=b''),
        ),
    ]
