# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-14 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singlepage', '0026_sp_img_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sp_img',
            name='owner',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
