# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-04 04:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singlepage', '0028_openhouse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openhouse',
            name='opendate1',
        ),
        migrations.RemoveField(
            model_name='openhouse',
            name='opendate2',
        ),
        migrations.AddField(
            model_name='openhouse',
            name='bgndate1',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='openhouse',
            name='bgndate2',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='openhouse',
            name='enddate1',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='openhouse',
            name='enddate2',
            field=models.DateTimeField(null=True),
        ),
    ]
