# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-14 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singlepage', '0029_auto_20180504_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing_for_sp',
            name='salestatus',
            field=models.CharField(choices=[('no', 'MLS'), ('yes', '\u5df2\u552e'), ('rent', '\u51fa\u79df'), ('rented', '\u5df2\u79df'), ('presale', '\u697c\u82b1'), ('dark', '\u6697\u76d8')], default='no', max_length=30),
        ),
    ]
