# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-23 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singlepage', '0032_listing_for_sp_distid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing_for_sp',
            name='distid',
            field=models.CharField(blank=True, choices=[('\u767d\u77f3', 'whiterock'), ('\u7d20\u91cc', 'Surrey'), ('\u65b0\u897f\u654f', 'newWestminster'), ('\u6e29\u54e5\u534e\u897f\u533a', 'VancouverWest'), ('\u672c\u62ff\u6bd4', 'Burnaby'), ('\u5217\u6cbb\u6587', 'Richmond'), ('\u897f\u6e29\u54e5\u534e', 'WestVan'), ('\u9ad8\u8d35\u6797', 'Coquitlam'), ('\u6e29\u54e5\u534e\u4e1c\u533a', 'Vancouvereast'), ('\u5317\u6e29', 'NorthVancouver'), ('\u4e09\u89d2\u6d32', 'delta'), ('\u5170\u91cc', 'Langley'), ('\u7c73\u900a', 'Mission'), ('\u963f\u4f2f\u8328\u798f\u5fb7', 'abbotsford'), ('\u5317\u7d20\u91cc', 'NorthSurrey'), ('\u5947\u5229\u74e6\u514b', 'Chilliwack'), ('\u970d\u666e', 'Hope'), ('\u5361\u5c14\u7279\u65af', 'Cultus'), ('\u73ab\u7470\u8c37', 'Rosedale'), ('\u65af\u9614\u7c73\u4ec0', 'squimish'), ('\u6ee1\u5730\u5b9d', 'PortMoody'), ('\u9633\u5149\u6d77\u5cb8', 'SunshineCoast'), ('\u67ab\u6811\u5cad', 'MapleRidge'), ('\u60e0\u65af\u52d2', 'Whistler'), ('\u5f6d\u4f2f\u987f', 'Pemberton'), ('\u62c9\u5fb7\u7eb3', 'Ladner'), ('\u514b\u6d1b\u5f17\u4ee3\u5c14', 'Cloverdale'), ('\u63aa\u74e6\u68ee', 'Tsawwassen'), ('\u5b9d\u4e91\u5c9b', 'Bowen'), ('\u9ad8\u8d35\u6797\u6e2f', 'PortCoquitlam'), ('\u8428\u8fea\u65af', 'Sardis'), ('\u5339\u7279\u8349\u539f', 'PittMeadows'), ('\u54c8\u91cc\u68ee', 'Harrison'), ('\u963f\u52a0\u897f', 'Agassiz'), ('\u4e9a\u7f57', 'Yarrow')], max_length=50),
        ),
    ]
