# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-23 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singlepage', '0034_auto_20180523_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing_for_sp',
            name='distid',
            field=models.CharField(blank=True, choices=[('WestVan', '\u897f\u6e29\u54e5\u534e'), ('VancouverWest', '\u6e29\u54e5\u534e\u897f\u533a'), ('Vancouvereast', '\u6e29\u54e5\u534e\u4e1c\u533a'), ('NorthVancouver', '\u5317\u6e29'), ('Burnaby', '\u672c\u62ff\u6bd4'), ('whiterock', '\u767d\u77f3'), ('Surrey', '\u7d20\u91cc'), ('Richmond', '\u5217\u6cbb\u6587'), ('Coquitlam', '\u9ad8\u8d35\u6797'), ('newWestminster', '\u65b0\u897f\u654f'), ('Chilliwack', '\u5947\u5229\u74e6\u514b'), ('delta', '\u4e09\u89d2\u6d32'), ('Langley', '\u5170\u91cc'), ('Mission', '\u7c73\u900a'), ('abbotsford', '\u963f\u4f2f\u8328\u798f\u5fb7'), ('NorthSurrey', '\u5317\u7d20\u91cc'), ('Hope', '\u970d\u666e'), ('Cultus', '\u5361\u5c14\u7279\u65af'), ('Rosedale', '\u73ab\u7470\u8c37'), ('squimish', '\u65af\u9614\u7c73\u4ec0'), ('PortMoody', '\u6ee1\u5730\u5b9d'), ('SunshineCoast', '\u9633\u5149\u6d77\u5cb8'), ('MapleRidge', '\u67ab\u6811\u5cad'), ('Whistler', '\u60e0\u65af\u52d2'), ('Pemberton', '\u5f6d\u4f2f\u987f'), ('Ladner', '\u62c9\u5fb7\u7eb3'), ('Cloverdale', '\u514b\u6d1b\u5f17\u4ee3\u5c14'), ('Tsawwassen', '\u63aa\u74e6\u68ee'), ('Bowen', '\u5b9d\u4e91\u5c9b'), ('PortCoquitlam', '\u9ad8\u8d35\u6797\u6e2f'), ('Sardis', '\u8428\u8fea\u65af'), ('PittMeadows', '\u5339\u7279\u8349\u539f'), ('Harrison', '\u54c8\u91cc\u68ee'), ('Agassiz', '\u963f\u52a0\u897f'), ('Yarrow', '\u4e9a\u7f57')], max_length=50),
        ),
    ]
