# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-02 00:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singlepage', '0036_auto_20180902_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing_for_sp',
            name='token',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='tokens',
            name='token',
            field=models.CharField(max_length=100),
        ),
    ]
