# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-26 23:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singlepage', '0038_listing_for_sp_sptype'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing_for_sp',
            name='isspread',
            field=models.CharField(blank=True, choices=[('0', '\u4e0d\u63a8\u5e7f'), ('1', '\u63a8\u5e7f')], default='1', max_length=10),
        ),
        migrations.AlterField(
            model_name='listing_for_sp',
            name='salestatus',
            field=models.CharField(choices=[('no', 'MLS'), ('yes', '\u5df2\u552e'), ('rent', '\u51fa\u79df'), ('rented', '\u5df2\u79df'), ('presale', '\u697c\u82b1'), ('dark', '\u6697\u76d8'), ('invalid', '\u672a\u5347\u6548')], default='invalid', max_length=30),
        ),
    ]
