# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-09 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singlepage', '0039_auto_20181126_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing_for_sp',
            name='isspread',
            field=models.CharField(blank=True, choices=[('0', '\u4e0d\u63a8\u5e7f'), ('1', '\u63a8\u5e7f')], default='0', max_length=10),
        ),
    ]
