# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2020-07-25 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singlepage', '0040_auto_20190709_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing_for_sp',
            name='mapspread',
            field=models.CharField(blank=True, choices=[('0', '\u4e0d\u63a8\u5e7f'), ('1', '\u63a8\u5e7f')], default='0', max_length=10),
        ),
    ]
