# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0002_delete_listings'),
    ]

    operations = [
        migrations.CreateModel(
            name='listingimgs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listingid', models.CharField(max_length=50)),
                ('img', models.FileField(upload_to='listings')),
            ],
        ),
        migrations.CreateModel(
            name='Listings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listingid', models.CharField(max_length=50, unique=True)),
                ('listingname', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('bedroom', models.CharField(max_length=100)),
                ('toilet', models.CharField(max_length=100)),
                ('parking', models.CharField(max_length=100)),
                ('tax', models.CharField(max_length=100)),
                ('housetype', models.CharField(max_length=100)),
                ('housestyle', models.CharField(max_length=100)),
                ('basement', models.CharField(max_length=100)),
                ('builddate', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('goodat', models.TextField()),
                ('corp', models.CharField(max_length=100)),
                ('warning', models.TextField()),
                ('url', models.CharField(max_length=100)),
            ],
        ),
    ]
