# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 15:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_listings_cityname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Listings',
        ),
    ]
