# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 16:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_listings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listings',
            old_name='area',
            new_name='areas',
        ),
        migrations.RenameField(
            model_name='listings',
            old_name='desc',
            new_name='describe',
        ),
    ]
