# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 17:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20160710_0057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listings',
            old_name='describe',
            new_name='intro',
        ),
    ]
