# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20160710_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='corp',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='listings',
            name='url',
            field=models.CharField(max_length=300),
        ),
    ]
