# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_article_eng_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='intro_eng',
            field=models.TextField(blank=True),
        ),
    ]
