# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20160712_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='eng_title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='listing',
            name='intro_eng',
            field=models.TextField(blank=True, default=''),
        ),
    ]
