# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20160713_2005'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing2',
            fields=[
                ('listingid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('listingname', models.CharField(max_length=100)),
                ('cityname', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=100)),
                ('areas', models.CharField(max_length=100)),
                ('postid', models.CharField(max_length=100)),
                ('housetype', models.CharField(max_length=100)),
                ('intro', models.TextField()),
                ('corp', models.CharField(max_length=500)),
                ('warning', models.TextField()),
                ('url', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Userimage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('imgtype', models.CharField(max_length=10)),
                ('img', models.FileField(upload_to='userimgs')),
            ],
        ),
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('usercity', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=100)),
                ('note', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('siteurl', models.CharField(max_length=100)),
                ('assistant', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('selfintro', models.TextField()),
                ('teamintro', models.TextField()),
                ('corpintro', models.TextField()),
                ('warning', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='listingimgs',
            new_name='Listingimg',
        ),
    ]
