# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_sharesite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sharesite',
            old_name='infoid',
            new_name='dataid',
        ),
        migrations.RemoveField(
            model_name='sharesite',
            name='htmlfile',
        ),
        migrations.AddField(
            model_name='sharesite',
            name='tempid',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sharesite',
            name='url',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
