# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20160802_2153'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempid', models.CharField(max_length=100)),
                ('userid', models.CharField(max_length=100)),
                ('temptype', models.CharField(max_length=100)),
                ('temp', models.CharField(max_length=100)),
            ],
        ),
    ]
