# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 14:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_template'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sharesite',
        ),
        migrations.DeleteModel(
            name='Template',
        ),
    ]
