# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20160802_2204'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sharesite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('htmlid', models.CharField(max_length=100)),
                ('tempid', models.CharField(blank=True, max_length=100)),
                ('userid', models.CharField(max_length=100)),
                ('dataid', models.CharField(max_length=100)),
                ('sharetype', models.CharField(max_length=30)),
                ('sharetime', models.DateTimeField(auto_now=True)),
                ('url', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempid', models.CharField(max_length=100)),
                ('userid', models.CharField(max_length=100)),
                ('temptype', models.CharField(max_length=100)),
                ('temp', models.CharField(max_length=100)),
                ('savetime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
