# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_sharesite_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharesite',
            name='dataid',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sharesite',
            name='sharetype',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
