# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-03 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20160802_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharesite',
            name='good',
            field=models.IntegerField(default=0),
        ),
    ]
