# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-03 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_sharesite_good'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sitecomment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('htmlid', models.CharField(max_length=100)),
                ('commtime', models.DateTimeField(auto_now=True)),
                ('userid', models.CharField(blank=True, max_length=100)),
                ('usercomment', models.CharField(max_length=500)),
            ],
        ),
    ]
