# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-06 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_sitecomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing2',
            name='price',
        ),
        migrations.AddField(
            model_name='listing2',
            name='opendate',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='listing2',
            name='price1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='listing2',
            name='price2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='listing2',
            name='proaddress',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='listing2',
            name='address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='listing2',
            name='areas',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='listing2',
            name='cityname',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='listing2',
            name='corp',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='listing2',
            name='housetype',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='listing2',
            name='intro',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='listing2',
            name='listingid',
            field=models.CharField(blank=True, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='listing2',
            name='listingname',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='listing2',
            name='postid',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='listing2',
            name='url',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='listing2',
            name='warning',
            field=models.TextField(blank=True),
        ),
    ]
