# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-06 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_auto_20160806_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingimg',
            name='imgtype',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
