# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-06 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_auto_20160806_2221'),
    ]

    operations = [
        migrations.CreateModel(
            name='Systemorder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('htmlid', models.CharField(max_length=100)),
                ('userid', models.CharField(max_length=100)),
                ('starttime', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
    ]
