# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-11 06:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_systemorder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userimage',
            old_name='username',
            new_name='userid',
        ),
    ]
