# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-11 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_sharesite_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharesite',
            name='comm',
            field=models.IntegerField(default=0),
        ),
    ]
