# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-17 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_auto_20160816_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='role',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
