# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-18 02:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_userinfo_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharesite',
            name='shared',
            field=models.CharField(default='0', max_length=1),
        ),
    ]
