# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-18 03:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_sharesite_shared'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecomment',
            name='commtype',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sitecomment',
            name='usercomment',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
