# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-18 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_advertisement'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='active',
            field=models.CharField(default='1', max_length=1),
        ),
    ]
