# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-20 05:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_advertisement_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='corp',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
