# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-22 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_userinfo_corp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Freeedit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataid', models.CharField(max_length=100)),
                ('userid', models.CharField(max_length=100)),
                ('note', models.CharField(max_length=500)),
                ('img', models.FileField(upload_to='freeedit')),
            ],
        ),
    ]
