# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-22 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_freeedit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freeedit',
            name='img',
            field=models.FileField(blank=True, upload_to='freeedit'),
        ),
        migrations.AlterField(
            model_name='freeedit',
            name='note',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
