# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-23 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_auto_20160822_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='freeedit',
            name='title',
            field=models.CharField(default='\u6211\u7684\u745e\u5b89\u5c45', max_length=100),
        ),
    ]
