# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-24 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_freeedit_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemorder',
            name='status',
            field=models.CharField(choices=[('pending', '\u5f85\u7ffb\u8bd1'), ('completed', '\u5f85\u5206\u4eab'), ('shared', '\u5f85\u8bc4\u4ef7'), ('commented', '\u5df2\u8bc4\u4ef7')], max_length=20),
        ),
    ]
