# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-29 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_auto_20160824_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='creditcard',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
