# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-30 09:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_userinfo_creditcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='datadate',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 8, 30, 9, 24, 33, 867000, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
