# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-01 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_listing_datadate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('couponid', models.CharField(max_length=100)),
                ('coupontype', models.CharField(max_length=100)),
                ('userid', models.CharField(max_length=100)),
                ('htmlid', models.CharField(max_length=100)),
                ('condi', models.CharField(max_length=100)),
                ('amt', models.IntegerField()),
                ('startdt', models.DateTimeField(auto_now=True)),
                ('enddt', models.DateTimeField(blank=True)),
                ('usable', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beginamt', models.IntegerField()),
                ('endamt', models.IntegerField()),
                ('percent', models.DecimalField(decimal_places=2, default=1, max_digits=16)),
            ],
        ),
    ]
