# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-01 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_coupon_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='condi',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='htmlid',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='discount',
            name='percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
    ]
