# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-02 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_auto_20160901_1730'),
    ]

    operations = [
#         migrations.RemoveField(
#             model_name='coupon',
#             name='id',
#         ),
#         migrations.AlterField(
#             model_name='coupon',
#             name='couponid',
#             field=models.AutoField(primary_key=True, serialize=False),
#         ),
    ]
