# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-02 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_delete_coupon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('couponid', models.AutoField(primary_key=True, serialize=False)),
                ('coupontype', models.CharField(max_length=100)),
                ('userid', models.CharField(max_length=100)),
                ('htmlid', models.CharField(blank=True, max_length=100)),
                ('condi', models.CharField(blank=True, max_length=100)),
                ('amt', models.IntegerField()),
                ('startdt', models.DateTimeField(auto_now=True)),
                ('enddt', models.DateTimeField(blank=True)),
                ('usable', models.CharField(max_length=1)),
            ],
        ),
    ]
