# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-02 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='amt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
    ]
