# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-06 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0054_telcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='cvs',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='enddt',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
