# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-18 02:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0055_auto_20160906_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='Custom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityname', models.CharField(max_length=100)),
                ('bedroom', models.CharField(max_length=100)),
                ('toilet', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('usercity', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=100)),
                ('pricezone', models.CharField(max_length=100)),
                ('buydate', models.CharField(max_length=100)),
                ('addservice', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=100)),
                ('problem', models.CharField(max_length=2000)),
                ('idea', models.CharField(max_length=2000)),
                ('tel', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
    ]
