# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-18 02:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0056_custom_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom',
            name='userid',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='custom',
            name='addservice',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='custom',
            name='bedroom',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='custom',
            name='buydate',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='custom',
            name='cityname',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='custom',
            name='pricezone',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='custom',
            name='tel',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='custom',
            name='toilet',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='custom',
            name='usercity',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='custom',
            name='username',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='email',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='idea',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='problem',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='tel',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='userid',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
