# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-18 02:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0057_auto_20160918_1030'),
    ]

    operations = [
#         migrations.AddField(
#             model_name='custom',
#             name='datadate',
#             field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 9, 18, 2, 39, 0, 971000, tzinfo=utc)),
#             preserve_default=False,
#         ),
#         migrations.AddField(
#             model_name='feedback',
#             name='datadate',
#             field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 9, 18, 2, 39, 0, 971000, tzinfo=utc)),
#             preserve_default=False,
#         ),
    ]
