# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-23 06:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0061_sharesite_temp'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='datadate',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 9, 23, 6, 27, 12, 541000, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
