# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-26 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0062_article_datadate'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='postid',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
