# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-28 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0063_userinfo_postid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Access_hitory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addr', models.CharField(blank=True, max_length=100)),
                ('actiontype', models.CharField(blank=True, max_length=20)),
                ('htmlid', models.CharField(blank=True, max_length=100)),
                ('htmltype', models.CharField(blank=True, max_length=10)),
                ('userid', models.CharField(blank=True, max_length=100)),
                ('datadate', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
