# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-09 06:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0065_sharesite_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing2',
            name='sd',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='listing2',
            name='unitnum',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
