# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-12 02:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0066_auto_20161009_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom',
            name='housetype',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
