# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-12 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0067_custom_housetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom',
            name='notes',
            field=models.CharField(blank=True, max_length=3000),
        ),
    ]
