# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-17 02:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0070_auto_20161014_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='adtype',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
