# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-17 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0071_advertisement_adtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wechat_info',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='wechat_info',
            name='headimgurl',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='wechat_info',
            name='privilege',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='wechat_info',
            name='unionid',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
