# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-17 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0072_auto_20161017_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wechat_info',
            name='headimgurl',
            field=models.CharField(blank=True, max_length=900),
        ),
    ]
