# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-20 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0073_auto_20161017_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='couponname',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
