# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-21 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0074_coupon_couponname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemorder',
            name='status',
            field=models.CharField(choices=[('pending', '\u5f85\u5904\u7406'), ('completed', '\u6b63\u5728\u63a8\u5e7f'), ('shared', '\u5df2\u7ed3\u675f')], max_length=20),
        ),
    ]
