# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-28 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0075_auto_20161021_1814'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charge_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(blank=True, max_length=100)),
                ('cardid', models.CharField(blank=True, max_length=100)),
                ('cvs', models.CharField(blank=True, max_length=10)),
                ('enddt', models.CharField(blank=True, max_length=30)),
                ('curr', models.CharField(blank=True, max_length=3)),
                ('amt', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('invoiced', models.CharField(blank=True, max_length=1)),
                ('datadate', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
