# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-28 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0076_charge_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoiced_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chargeids', models.CharField(blank=True, max_length=1000)),
                ('userid', models.CharField(blank=True, max_length=100)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('addr', models.CharField(blank=True, max_length=1000)),
                ('postid', models.CharField(blank=True, max_length=100)),
                ('datadate', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
