# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-28 13:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0077_invoiced_history'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': '\u70ed\u70b9\u6587\u7ae0', 'verbose_name_plural': '\u70ed\u70b9\u6587\u7ae0'},
        ),
        migrations.AlterModelOptions(
            name='listing',
            options={'verbose_name': '\u5728\u552e\u623f\u6e90', 'verbose_name_plural': '\u5728\u552e\u623f\u6e90'},
        ),
    ]
