# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-28 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0078_auto_20161028_2109'),
    ]

    operations = [
        migrations.CreateModel(
            name='System_msg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(blank=True, max_length=100)),
                ('msgtype', models.CharField(blank=True, max_length=20)),
                ('blacklist', models.CharField(blank=True, max_length=5000)),
                ('msg', models.CharField(blank=True, max_length=5000)),
                ('datadate', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '\u7cfb\u7edf\u901a\u77e5',
                'verbose_name_plural': '\u7cfb\u7edf\u901a\u77e5',
            },
        ),
    ]
