# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-31 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0080_system_msg_msgtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='img1',
            field=models.FileField(default='', upload_to='feedback'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='img2',
            field=models.FileField(default='', upload_to='feedback'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='img3',
            field=models.FileField(default='', upload_to='feedback'),
        ),
    ]
