# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-01 02:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0081_auto_20161031_1347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='system_msg',
            old_name='blacklist',
            new_name='target',
        ),
    ]
