# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-01 02:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0083_system_msg_msgstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='system_msg',
            name='createdate',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 11, 1, 2, 21, 13, 814000, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
