# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-01 02:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0084_system_msg_createdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system_msg',
            name='msgstatus',
            field=models.CharField(choices=[('pending', '\u5f85\u53d1\u9001'), ('sended', '\u5df2\u53d1\u9001')], max_length=20),
        ),
    ]
