# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-01 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0085_auto_20161101_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system_msg',
            name='msgtype',
            field=models.CharField(default='text', max_length=20),
        ),
    ]
