# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-02 02:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0086_auto_20161101_1037'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publish_apk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versionName', models.CharField(blank=True, max_length=100)),
                ('apkname', models.CharField(blank=True, max_length=100)),
                ('apkinfo', models.CharField(blank=True, max_length=2000)),
                ('apkurl', models.CharField(blank=True, max_length=1000)),
                ('datadate', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '\u5e94\u7528\u66f4\u65b0',
                'verbose_name_plural': '\u5e94\u7528\u66f4\u65b0',
            },
        ),
    ]
