# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-09 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0089_publish_apk_versioncode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_type',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
    ]
