# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-11 01:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0090_auto_20161109_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freeedit',
            name='note',
            field=models.CharField(blank=True, max_length=5000),
        ),
    ]
