# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-17 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0091_auto_20161111_0952'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisement',
            options={'verbose_name': '\u5e7f\u544a', 'verbose_name_plural': '\u5e7f\u544a'},
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='adtype',
            field=models.CharField(choices=[('fx', '\u53d1\u73b0\u9875\u5e7f\u544a'), ('dz', '\u79c1\u4eba\u8ba2\u5236\u9875\u5e7f\u544a')], max_length=20),
        ),
    ]
