# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-18 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0092_auto_20161117_2328'),
    ]

    operations = [
        migrations.CreateModel(
            name='School_dist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schoolid', models.CharField(blank=True, max_length=100)),
                ('schoolname', models.CharField(blank=True, max_length=100)),
                ('schoolcity', models.CharField(blank=True, max_length=100)),
                ('schooltype', models.CharField(blank=True, max_length=100)),
                ('rank1', models.CharField(blank=True, max_length=100)),
                ('rank2', models.CharField(blank=True, max_length=100)),
                ('parentsin', models.CharField(blank=True, max_length=100)),
                ('testnum', models.CharField(blank=True, max_length=100)),
                ('noneng', models.CharField(blank=True, max_length=100)),
                ('fran', models.CharField(blank=True, max_length=100)),
                ('spec', models.CharField(blank=True, max_length=100)),
                ('tel', models.CharField(blank=True, max_length=100)),
                ('studentnum', models.CharField(blank=True, max_length=100)),
                ('schooladdr', models.CharField(blank=True, max_length=100)),
                ('registnum', models.CharField(blank=True, max_length=100)),
                ('schoolhead', models.CharField(blank=True, max_length=100)),
                ('fax', models.CharField(blank=True, max_length=100)),
                ('datadate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='listing',
            name='schoolid',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
