# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-30 02:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0093_auto_20161118_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='datadate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
