# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-09 02:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0094_auto_20161130_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='adtype',
            field=models.CharField(choices=[('fx', '\u53d1\u73b0\u9875\u5e7f\u544a'), ('dz', '\u79c1\u4eba\u8ba2\u5236\u9875\u5e7f\u544a'), ('atc1', '\u6587\u7ae0\u5217\u8868\u9875\u5e7f\u544a(\u5927)'), ('atc2', '\u6587\u7ae0\u5217\u8868\u9875\u5e7f\u544a(\u5c0f)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='listing',
            name='cityname',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
