# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-17 02:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0095_auto_20170109_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='good',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listing',
            name='visit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listing2',
            name='datadate',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2017, 1, 17, 2, 53, 41, 817000, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing2',
            name='good',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listing2',
            name='visit',
            field=models.IntegerField(default=0),
        ),
    ]
