# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0096_auto_20170117_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='adtype',
            field=models.CharField(choices=[('fx', '\u53d1\u73b0\u9875\u5e7f\u544a'), ('dz', '\u79c1\u4eba\u8ba2\u5236\u9875\u5e7f\u544a'), ('atc1', '\u6587\u7ae0\u5217\u8868\u9875\u5e7f\u544a(\u5927)'), ('atc2', '\u6587\u7ae0\u5217\u8868\u9875\u5e7f\u544a(\u5c0f)'), ('yz', '\u9a8c\u8bc1\u9875\u5e7f\u544a')], max_length=20),
        ),
    ]
