# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0097_auto_20170215_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemorder',
            name='status',
            field=models.CharField(choices=[('pending', '\u5f85\u5904\u7406'), ('completed', '\u6b63\u5728\u63a8\u5e7f'), ('shared', '\u5df2\u7ed3\u675f'), ('commented', '\u5df2\u8bc4\u4ef7')], max_length=20),
        ),
    ]
