# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 03:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0098_auto_20170215_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='adtype',
            field=models.CharField(choices=[('fx', '\u53d1\u73b0\u9875\u5e7f\u544a'), ('dz', '\u79c1\u4eba\u8ba2\u5236\u9875\u5e7f\u544a'), ('atc1', '\u6587\u7ae0\u5217\u8868\u9875\u5e7f\u544a(\u5927)'), ('atc2', '\u6587\u7ae0\u5217\u8868\u9875\u5e7f\u544a(\u5c0f)'), ('yz', '\u9a8c\u8bc1\u9875\u5e7f\u544a'), ('hy', '\u8fdb\u5165APP\u6b22\u8fce\u9875')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sharesite',
            name='sharetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
