# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-27 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0100_auto_20170327_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='good',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='visit',
            field=models.IntegerField(default=0),
        ),
    ]
