# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-19 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0104_auto_20171201_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingimg',
            name='listingid',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
