# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-08 05:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='agent_auth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=100)),
                ('bgndate', models.DateTimeField(auto_now_add=True)),
                ('enddate', models.DateTimeField()),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('status', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': '\u7ecf\u7eaa\u8ba4\u8bc1\u8868',
                'verbose_name_plural': '\u7ecf\u7eaa\u8ba4\u8bc1\u8868',
            },
        ),
        migrations.CreateModel(
            name='agent_card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=100)),
                ('holder', models.CharField(blank=True, max_length=100)),
                ('cardno', models.CharField(blank=True, max_length=100)),
                ('expire', models.CharField(blank=True, max_length=10)),
                ('cvs', models.CharField(blank=True, max_length=3)),
                ('postid', models.CharField(blank=True, max_length=100)),
                ('cardtype', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'verbose_name': '\u4fe1\u7528\u5361\u4fe1\u606f\u8868',
                'verbose_name_plural': '\u4fe1\u7528\u5361\u4fe1\u606f\u8868',
            },
        ),
        migrations.CreateModel(
            name='agent_img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=100)),
                ('imgtype', models.CharField(blank=True, max_length=100)),
                ('img', models.FileField(blank=True, upload_to='agentimgs')),
            ],
            options={
                'verbose_name': '\u7ecf\u7eaa\u56fe\u7247',
                'verbose_name_plural': '\u7ecf\u7eaa\u56fe\u7247',
            },
        ),
        migrations.CreateModel(
            name='agent_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=100)),
                ('username', models.CharField(blank=True, max_length=100)),
                ('tel', models.CharField(blank=True, max_length=100)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('note', models.CharField(blank=True, max_length=100)),
                ('agenttype', models.CharField(blank=True, max_length=10)),
                ('website', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('selfintro', models.TextField(blank=True)),
                ('selfintro_cn', models.TextField(blank=True)),
                ('corpintro', models.TextField(blank=True)),
                ('corpintro_cn', models.TextField(blank=True)),
                ('teamintro', models.TextField(blank=True)),
                ('teamintro_cn', models.TextField(blank=True)),
                ('corp', models.CharField(blank=True, max_length=100)),
                ('postid', models.CharField(blank=True, max_length=20)),
                ('head', models.FileField(blank=True, upload_to='agentimgs')),
                ('qrcode', models.FileField(blank=True, upload_to='agentimgs')),
                ('logo', models.FileField(blank=True, upload_to='agentimgs')),
                ('username2', models.CharField(blank=True, max_length=100)),
                ('tel2', models.CharField(blank=True, max_length=100)),
                ('email2', models.CharField(blank=True, max_length=100)),
                ('head2', models.FileField(blank=True, upload_to='agentimgs')),
                ('qrcode2', models.FileField(blank=True, upload_to='agentimgs')),
                ('country', models.CharField(blank=True, max_length=100)),
                ('prov', models.CharField(blank=True, max_length=100)),
                ('group', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('county', models.CharField(blank=True, max_length=100)),
                ('datadate', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '\u7ecf\u7eaa\u7528\u6237\u4fe1\u606f\u8868',
                'verbose_name_plural': '\u7ecf\u7eaa\u7528\u6237\u4fe1\u606f\u8868',
            },
        ),
        migrations.CreateModel(
            name='tmp_token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=100)),
                ('token', models.CharField(blank=True, max_length=100)),
                ('datadate', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
