# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-03 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent_auth',
            name='service',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='agent_auth',
            name='enddate',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='agent_auth',
            name='status',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
