# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-03 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20180503_2315'),
    ]

    operations = [
        migrations.CreateModel(
            name='cust_message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=100)),
                ('custname', models.CharField(blank=True, max_length=100)),
                ('custemail', models.CharField(blank=True, max_length=100)),
                ('custemsg', models.CharField(blank=True, max_length=2000)),
                ('datadate', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
