# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-03 16:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_cust_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cust_message',
            old_name='custemsg',
            new_name='custmsg',
        ),
    ]
