# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-07 04:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20180504_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent_info',
            name='fname',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='agent_info',
            name='lname',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
