# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-09 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20180507_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent_auth',
            name='cardno',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='agent_auth',
            name='enddate',
            field=models.DateTimeField(null=True),
        ),
    ]
