# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-12 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20180509_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent_auth',
            name='status',
            field=models.CharField(choices=[('paid', '\u5df2\u652f\u4ed8'), ('not paid', '\u672a\u652f\u4ed8')], default='not paid', max_length=10),
        ),
        migrations.AlterField(
            model_name='agent_card',
            name='cardtype',
            field=models.CharField(choices=[('0', '\u5386\u53f2\u4fe1\u7528\u5361'), ('1', '\u9ed8\u8ba4\u4ed8\u6b3e\u5361'), ('deleted', '\u5df2\u5220\u9664\u7684\u5361')], default='1', max_length=10),
        ),
    ]
