# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-12 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20180512_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent_auth',
            name='bgndate',
            field=models.DateTimeField(null=True),
        ),
    ]
