# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-12 23:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20180512_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent_auth',
            name='service',
            field=models.CharField(choices=[('vip', '\u4f1a\u5458\u670d\u52a1 ($288/\u5e74)'), ('auth', '\u7ffb\u8bd1\u53ca\u8ba4\u8bc1\u670d\u52a1\u8d39 ($79)'), ('sp', 'Smartflyer ($99/Listing)')], default='vip', max_length=100),
        ),
    ]
