# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-25 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_agent_info_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent_info',
            name='active',
            field=models.CharField(choices=[('1', '\u662f'), ('0', '\u5426')], default='1', max_length=10),
        ),
    ]
