# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-25 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_auto_20180525_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent_auth',
            name='token',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
