# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-30 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_agent_auth_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent_auth',
            name='invoice',
            field=models.FileField(blank=True, upload_to='sp_invoice'),
        ),
    ]
