# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-28 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_auto_20180531_1246'),
    ]

    operations = [
        migrations.CreateModel(
            name='email_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=100)),
                ('fname', models.CharField(blank=True, max_length=100)),
                ('lname', models.CharField(blank=True, max_length=100)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('datadate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
