# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-28 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_email_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent_info',
            name='emailscd',
            field=models.CharField(choices=[('weekly', '\u6bcf\u5468\u53d1\u9001'), ('pause', '\u6682\u505c\u53d1\u9001')], default='pause', max_length=10),
        ),
    ]
