# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-09 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_agent_info_emailscd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent_auth',
            name='service',
            field=models.CharField(choices=[('vip', '\u4f1a\u5458\u670d\u52a1 ($288/\u5e74)'), ('auth', '\u7ffb\u8bd1\u53ca\u8ba4\u8bc1\u670d\u52a1\u8d39 ($79)'), ('sp', 'Smartflyer ($99/Listing)'), ('domain', '\u7ecf\u7eaa\u4e3b\u9875\u57df\u540d ($20)'), ('engagement', '\u4e70\u5bb6\u5438\u5f15\u5957\u9910 ($360)')], default='vip', max_length=100),
        ),
    ]
