# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-11 23:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_auto_20190709_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='cust_message',
            name='mls',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cust_message',
            name='msgtype',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
