# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-11 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0020_auto_20190714_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='email_list',
            name='msg',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='email_list',
            name='src',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
