# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2020-07-25 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0022_auto_20190822_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent_auth',
            name='service',
            field=models.CharField(choices=[('vip', '\u4f1a\u5458\u670d\u52a1 ($288/\u5e74)'), ('auth', '\u7ffb\u8bd1\u53ca\u8ba4\u8bc1\u670d\u52a1\u8d39 ($79)'), ('sp', 'Smartflyer ($99/Listing)'), ('subscription', '2020 Subscription Package'), ('domain', '\u7ecf\u7eaa\u4e3b\u9875\u57df\u540d ($20)'), ('engagement', '\u4e70\u5bb6\u5438\u5f15\u5957\u9910 ($360)'), ('diyPage', '\u7ecf\u7eaa\u4eba\u9875\u9762\u6837\u5f0f\u8df3\u8f6c,\u53ef\u914d\u7f6e\u4e0d\u540c\u7684CSS\u548cHTML\u6837\u5f0f($499/year)')], default='vip', max_length=100),
        ),
        migrations.AlterField(
            model_name='agent_info',
            name='emailscd',
            field=models.CharField(choices=[('weekly', '\u6bcf\u5468\u53d1\u9001'), ('pause', '\u6682\u505c\u53d1\u9001')], default='weekly', max_length=10),
        ),
    ]
