# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-14 03:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sourceid', models.CharField(max_length=50)),
                ('sourcename', models.CharField(max_length=50)),
                ('sourcetype', models.CharField(max_length=50)),
                ('sourcepermi', models.CharField(max_length=50)),
                ('sourcefrom', models.CharField(max_length=50)),
                ('datais', models.CharField(max_length=50)),
                ('isenable', models.CharField(max_length=1)),
            ],
        ),
    ]
