# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-19 07:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bi', '0003_auto_20160719_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_data',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='user_data',
            name='title',
        ),
    ]
