# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-29 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bi', '0007_auto_20160727_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=50)),
                ('tempid', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=10)),
                ('tempname', models.CharField(blank=True, max_length=50)),
                ('savetime', models.DateTimeField(auto_now=True)),
                ('data', models.TextField()),
            ],
        ),
    ]
