# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 03:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bi', '0009_template_temptype'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='url',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
