# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-04 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bi', '0010_template_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='template',
            old_name='data',
            new_name='htmldata',
        ),
        migrations.RenameField(
            model_name='template',
            old_name='url',
            new_name='htmlurl',
        ),
        migrations.AddField(
            model_name='template',
            name='divdata',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='template',
            name='divurl',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
