# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-05 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bi', '0011_auto_20160804_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='htmldata',
            field=models.TextField(blank=True),
        ),
    ]
