# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-15 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bi', '0013_auto_20160815_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='chartname',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
