# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-16 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bi', '0014_user_data_chartname'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmpdata',
            name='srctab',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='user_data',
            name='srctab',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
