# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-09 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bi', '0015_auto_20160816_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='datatype',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
