# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-25 02:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bi', '0016_auto_20161109_1012'),
    ]

    operations = [
        migrations.CreateModel(
            name='Echarts_Json_columns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chartid', models.CharField(max_length=100)),
                ('tablename', models.CharField(max_length=100)),
                ('echart_columns', models.CharField(max_length=100)),
                ('computation_rule', models.CharField(blank=True, max_length=20, null=True)),
                ('chart_type', models.CharField(blank=True, max_length=20, null=True)),
                ('xAxis_or_yAxis', models.CharField(max_length=20)),
                ('yAxisIndex', models.CharField(blank=True, max_length=20, null=True)),
                ('scaler', models.IntegerField()),
                ('where_rule', models.CharField(max_length=200)),
                ('savetime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Echarts_Json_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chartid', models.CharField(max_length=100)),
                ('Json_file_name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('subtext', models.CharField(blank=True, max_length=100, null=True)),
                ('xunit', models.CharField(blank=True, max_length=100, null=True)),
                ('lyunit', models.CharField(blank=True, max_length=100, null=True)),
                ('ryunit', models.CharField(blank=True, max_length=100, null=True)),
                ('lyname', models.CharField(blank=True, max_length=100, null=True)),
                ('ryname', models.CharField(blank=True, max_length=100, null=True)),
                ('formatter', models.CharField(blank=True, max_length=100, null=True)),
                ('report_sql', models.CharField(blank=True, max_length=500, null=True)),
                ('flag', models.CharField(max_length=100)),
                ('savetime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
