# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-25 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bi', '0017_echarts_json_columns_echarts_json_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='sourcedb',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='source',
            name='sourceip',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='source',
            name='sourcepasswd',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='source',
            name='sourceport',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='source',
            name='sourceuser',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
