# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-25 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bi', '0019_source_realtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmpdata',
            name='sqls',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='user_data',
            name='srcid',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
