# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-25 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bi', '0020_auto_20161125_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmpdata',
            name='rttype',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='user_data',
            name='rttype',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
