# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-12 05:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bi', '0022_tmpdata_jsn'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmpdata',
            name='timewindow',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='user_data',
            name='timewindow',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
