# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-21 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bi', '0023_auto_20161212_1345'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source_file',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sourceid', models.CharField(max_length=50)),
                ('filetype', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='srcfile')),
            ],
        ),
    ]
