# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bi', '0025_auto_20161221_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='theme',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
