from django.conf.urls import url
from views import *

urlpatterns = [
    url(r'^signup1/', signup1),
    url(r'^signup2/', signup2),
    url(r'^sendmsg/', send_mobile),
    url(r'^login/', signin),
    url(r'^wxlogin/', wxsignin),
    url(r'^wxbind/', wx_binding),
    url(r'^logout/', logout),
    url(r'^haslogin/', is_login),
    url(r'^getpasswd/', get_passwd),
    url(r'^setpasswd/', set_passwd),
    url(r'^save/template/', save_temp),
    url(r'^get/template/', get_temp),
    url(r'^make/html/', mk_html),
    url(r'^share/html/', share_html),
    url(r'^freedit/', free_edit),
    url(r'^get/listing1/(?P<lid>[0-9]+)', get_listing1_html),
    url(r'^get/listing2/(?P<lid>[0-9]+)', get_listing2_html),
    url(r'^get/mysite/(?P<lid>[0-9]+)', get_mysite_html),
    url(r'^get/article/(?P<lid>[0-9]+)', get_article_html),
    url(r'^get/free/(?P<lid>[0-9]+)', get_free_edit_html),
    url(r'^submit/comment/', submit_comment),
    url(r'^get/comment/', get_comments),
    url(r'^get/listing1/', get_listing1),
    url(r'^get/listing2/', get_listing2),
    url(r'^save/listing2/', save_listing2),
    url(r'^save/userinfo/', save_userinfo),
    url(r'^get/userinfo/', get_userinfo),
    url(r'^get/cityinfo/', get_cityinfo),
    url(r'^get/atypeinfo/', get_article_type_info),
    url(r'^get/articles/', get_articles),
    url(r'^get/rcmd/', get_recommendation),
    url(r'^get/school/listings/', get_school_listings),
    url(r'^get/shares/', get_shares),
    url(r'^save/userimg/', save_userimg),
    url(r'^save/listingimg/', save_listingimg),
    url(r'^charge/', charge),
    url(r'^custom/', private_custom),
    url(r'^get/custom/', get_private_custom),
    url(r'^feedback/', feedback),
    url(r'^get/coupons/', get_coupon),
    url(r'^get/ad/', get_ad),
    url(r'^get/chargehis/', get_charge_history),
    url(r'^get/invoice/', get_invoice),
    url(r'^get/sysmsg/', get_sys_msg),
    url(r'^get/userinfohx/', get_userinfo_hx),
    url(r'^download/', download_app),
    url(r'^todownload/', download_site,name = 'downloadpage'),
    url(r'^update/', update_app),
    url(r'^get/static/', get_static),
    url(r'^xjq/login/', xjq_login),
    url(r'^xjq/signup/', xjq_signup),
    url(r'^xjq/', xjq),
    url(r'^test/', test),
]
