
from django.conf.urls import url
from bi.views import *

urlpatterns = [
    url(r'^$', index),
    url(r'^login/$', login),
    url(r'^logout/$', tologout),
    url(r'^haslogin/$', has_login),
    url(r'^add/source/$', addsource,name = 'source'),
    url(r'^get/sourcename/$', getsourcename,name = 'sourcename'),
    url(r'^get/sourceinfo/$', getsourceinfo,name = 'sourceinfo'),
    url(r'^get/sourceinfo2/$', getsourceinfo2,name = 'sourceinfo2'),
    url(r'^add/excel/$', addexcel,name = 'excel'),
    url(r'^upload/excel/$', upload_excel,name = 'upexcel'),
    url(r'^add/mysql/$', addmysql,name = 'mysql'),
    url(r'^add/chart/$', addchart,name = 'chart'),
    url(r'^get/perm/$', getperm,name = 'perm'),
    url(r'^conf/connstr/$', confconn,name = 'connstr'),
    url(r'^conf/dbtab/$', conftab,name = 'dbtab'),
    url(r'^conf/makelinedata/$', make_line_data,name = 'makelinedata'),
    url(r'^conf/makepiedata/$', make_pie_data,name = 'makepiedata'),
    url(r'^conf/makemapdata/$', make_map_data,name = 'makemapdata'),
    url(r'^conf/makedashboarddata/$', make_dashboard_data,name = 'makedashboarddata'),
    url(r'^conf/makethermodynamicdata/$', make_thermodynamic_data,name = 'makethermodynamicdata'),
    url(r'^conf/distribute/$', monitoring, name = 'monitoring'),
    url(r'^get/userchart/$',getchart, name = 'getchart'),
    url(r'^rtchart/(?P<dataid>[0-9]+)$',get_realtime_chart, name = 'rtchart'),
    url(r'^get/temptype/$', read_temptype,name = 'temptype'),
    url(r'^get/datatype/$', read_datatype,name = 'datatype'),
    url(r'^add/template/$',savetemp,name='savetemplatex'),
    url(r'^get/body/(?P<htmlid>[0-9]+)$',getbody,name='body'),
    url(r'^get/div/$',getdiv,name='div'),
    url(r'^delchart/$',del_chart,name='delchart'),
    url(r'^delsource/$',del_source,name='delsource'),
    url(r'^tabofdb/$',read_tab,name='tabofdb'),
    url(r'^geturls/$',get_urls,name='geturls'),
    url(r'^updateurl/$',update_url,name='updateurl'),
    url(r'^delurl/$',del_url,name='delurl'),
    url(r'^getjson/$',get_json,name='getjson'),
    url(r'^page1/$',gettest1,name='page1'),
    url(r'^page2/$',gettest2,name='page2'),
    url(r'^page3/$',gettest3,name='page3'),
]
