from django.conf.urls import url
from views import *

urlpatterns = [
    #     url(r'^listing/spread/', get_listing_spread),
    #     url(r'^mysite/spread/', get_mysite_spread),
    url(r'^app/', downloadapp),
    url(r'^listing1/(?P<mls>\w+)/(?P<htmlid>.*)', listingpage),
    url(r'^listing1/$', listingpage_redirect),
    url(r'^listing2/', listingpage2),
    url(r'^houses/(?P<items>.*)', get_listings),
    url(r'^listings/(?P<items>.*)', get_listings_redirect),
    url(r'^rcmd/listing/', get_rcmd_listing),
    #     url(r'^get/listings/', get_listings),
    url(r'^call/agent/', call_agent),
    url(r'^agentlist/(?P<items>.*)', agent_list_page),
    url(r'^agent/(?P<uid>[0-9]+)', agent_page),
    url(r'^agent2/(?P<uid>[0-9]+)', agent2_page),
    url(r'^agent3/(?P<uid>[0-9]+)', agent3_page),
    url(r'^agent4/(?P<uid>[0-9]+)', agent4_page),
    url(r'^update/visit', update_visit),
    url(r'^add/email', add_email),
    url(r'^agent/$', agent_page_redirect),
    url(r'^news/history/', news_shared),
    url(r'^search/', search_listing),
    url(r'^comment/', save_comment),
    url(r'^get/comment/', get_comments),
    url(r'^share/history/', get_share_history),
    url(r'^get/agents/', agent_list),
    url(r'^find/agent/', find_agent),
    url(r'^other/agent/', get_some_agent),
    url(r'^map/listings/', map_listings),
    url(r'^m/listings/', map_listings_m),
    url(r'^zone/listings/', get_area_listings),

    url(r'^get/countries/', to_get_countries),
    url(r'^get/provs/', to_get_provs),
    url(r'^get/groups/', to_get_groups),
    url(r'^get/cities/', to_get_cities),
    url(r'^get/counties/', to_get_counties),

    url(r'^signup/', sign_up),
    url(r'^signin/', sign_in),
    url(r'^postinfo/', update_agent_info),
    url(r'^postimg/', upload_img),
    url(r'^delimg/', del_img),
    url(r'^addcard/', add_card),
    url(r'^delcard/', del_card),
    url(r'^defcard/', default_card),
    url(r'^topasswd/', get_passwd_code),
    url(r'^postpasswd/', update_passwd),
    url(r'^cmt/info/', leave_message),
    url(r'^postopendate/', update_opendate),
    url(r'^get-invoice/', askfor_invoice),
    url(r'^get/singlepages/', get_singlepages),
    url(r'^page/signin/', login_page),
    url(r'^page/signup/', signup_page),
    url(r'^console/', agent_console_page),
    url(r'^passwd/', passwd_page),
    url(r'^small/img/', small_agent),
    url(r'^logout/', log_out),
    url(r'^upload/list/', upload_email_list),
    url(r'^set/schedule/', set_schedule),
    url(r'^set/salestatus/', set_sale_status),
    url(r'^set/price/', set_price),
    url(r'^add/listing/', add_listing),
    url(r'^reciprocity/', realtyninja_page),
    url(r'^van/', bi_page_vancouver),
    url(r'^westvan/', bi_page_westvan),
    url(r'^burnaby/', bi_page_burnaby),
    url(r'^surrey/', bi_page_surrey),
    url(r'^coquitlam/', bi_page_coquitlam),
    url(r'^whiterock/', bi_page_whiterock),
    url(r'^portmoody/', bi_page_portmoody),
    url(r'^richmond/', bi_page_richmond),
    url(r'^northvan/', bi_page_northvan),
    url(r'^northsurrey/', bi_page_northsurrey),
    url(r'^newwestminster/', bi_page_newwestminster),
    url(r'^whistler/', bi_page_whistler),
    url(r'^gen/token/', gen_token),
    url(r'^sync/user/', sync_user),
]
